[package]
name = "blst_ringct"
version = "0.1.0"
edition = "2021"

[dependencies]
# blstrs = "0.4.1"
# blstrs = { git = "https://github.com/davidrusu/blstrs.git", branch="bulletproofs-fixes" }
blstrs = { git = "https://github.com/dan-da/blstrs", branch = "blst_version_bump_pr" }

rand_core = "0.6.3"
thiserror = "1"
tiny-keccak = { version = "2.0", features = ["sha3"] }
merlin = { version = "3", default-features = false }
bulletproofs = { git = "https://github.com/grumbach/blst-bulletproofs.git", branch="pump-blst-version" }
serde = { version = "1.0.130", optional = true }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
